---
- name: Create groups
  win_domain_group:
    name: "{{ item.group }}"
    scope: "{{ group_scope }}"
  loop: "{{ user_info }}"

- name: Create users
  win_domain_user:
    name: "{{ item.username }}"
    firstname: "{{ item.firstname }}"
    surname: "{{ item.surname }}"
    password: "{{ item.password }}"
    state: present
    email: "{{ item.username }}@{{ ad_domain_name }}"
    update_password: on_create
    groups:
      - "{{ item.group }}"
  loop: "{{ user_info }}"