---
- name: Create users
  win_domain_user:
    name: "{{ item.username }}"
    firstname: "{{ item.firstname }}"
    surname: "{{ item.surname }}"
    password: "{{ item.password }}"
    state: present
    groups:
      - "{{ item.group }}"
  loop: "{{ userlist }}"