---
- name: Install AD
  win_feature:
    name: AD-Domain-Services
    state: present

- name: ensure AD configured
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ansible_password }}"
  register: domaininstall

- name: reboot
  win_reboot:
    msg: "rebooting {{ inventory_hostname }}"
  when: domaininstall.reboot_required

- name: Setup my AD
  win_domain_controller:
    domain_admin_user: "{{ ad_admin_user }}"
    domain_admin_password: "{{ ansible_password }}"
    state: domain_controller
    dns_domain_name: "{{ ad_domain_name }}"