---
- name: "Install {{ service_name }}"
  win_chocolatey:
    name: "{{ package_name }}"
    state: present
    package_params: "{{ parameters }}"
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: "Start {{ service_name }}"
  win_service:
    name: "{{ service_name }}"
    state: started
    start_mode: auto
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: "Firewall rule for {{ service_name }}"
  win_firewall_rule:
    name: "{{ service_name }}"
    localport: "{{ local_port }}"
    action: allow
    direction: in
    protocol: "{{ protocol_name }}"
    state: present
    enabled: yes